apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helmsights

commonLabels:
  app.kubernetes.io/name: helmsights
  app.kubernetes.io/part-of: helmsights

resources:
  - ../../crd/helmsightsreport.yaml
  - ../../rbac/serviceaccount.yaml
  - ../../rbac/role.yaml
  - ../../rbac/rolebinding.yaml
  - deployment.yaml
  - service.yaml
